### ISSUE TITLE
Better sensor support

### ISSUE THREAD

**Issue by davidedelvento** [stem-piano/stem-piano-g-main#1]
I think that instead of using regular aluminum extrusions, it'd be much better using the specialty ones I link below.

Advantages of specialty extrusions:

* extreme sturdiness, lack of vibrations, flex and bends: things stay where you put them (I know you had an issue with this)
* very easy adjustment of sensors possible: need to move them a bit left or right? Just a loosen the bolt, move them and tighten back!
* much easier manufacturing and assembly: just put the sensors where you need them! No measurement, no drilling and no drilling mistakes if you put them in the wrong place!

The extrusions I used are for the hammer sensors are https://us.misumi-ec.com/vona2/detail/110302684530/ and for the key (dampers) sensors are https://us.misumi-ec.com/vona2/detail/110302261730/ but of course many alternatives exist. I prefer MISUMI as the market leader in the field having a top-notch product, rather than saving a few dollars and encountering flex problems, or difficulty matching the nuts.

Can see some CAD rendering of both sensor and damper assembly, with a bit more description at https://pianoclack.com/forum/d/542-update-on-piano-conversion/21

You may comment about this option at https://github.com/stem-piano/stem-piano-g-main/blob/main/documentation/construction_subsections/subsection5_action_frame.md and at https://github.com/stem-piano/stem-piano-g-main/blob/main/documentation/component_manual.md#sensor-rail

**Comment by gzweigle** [comment]
added to documentation and linked to this issue in documentation (to keep the information visible)

**Comment by davidedelvento** [comment]
Just to make sure somebody does not overlook this, since it's buried in the scrolldown of the forum link I've already posted: going in post https://pianoclack.com/forum/d/542-update-on-piano-conversion/49 and scrolling further down you will find detailed installation instructions for my sensorboars on the extruded rails. Even if your sensorboards are different, the instructions will look very close, the only important thing is that the holes in the sensorboards should match the pitch between the slots
